replace fixed size with real device size
taehwandev/MediaProjectionExample pull request #2
Opened 2020-12-23 07:51 UTC by holykss

2020-12-31 06:54 UTC, taehwandev requested changes

2020-12-31 06:54 UTC, taehwandev commented on mediaProjectionLibrary/src/main/java/tech/thdev/media_projection_library/util/DeviceSize.kt
> +class DeviceSize(context: Context) {
Util 인데 class 인건 이상하네요.
context 역시 이렇게 들고 있는건 좋지 않습니다.
util 형태로 변경해주세요.

2020-12-31 06:56 UTC, taehwandev commented on mediaProjectionLibrary/src/main/java/tech/thdev/media_projection_library/ui/MediaProjectionAccessService.kt
> +                height: Int = DeviceSize(context).size.height
default의 의미 역시 screenSize가 아닙니다. 외부에서 주입할 때 DeviceSize를 적용해서 넘겨주도록 돌려주세요.

2020-12-31 07:48 UTC, holykss commented on mediaProjectionLibrary/src/main/java/tech/thdev/media_projection_library/util/DeviceSize.kt
> +class DeviceSize(context: Context) {
context는 생성자에서만 parameter 로서 소모되어 들고 있다고 생각하지 않습니다.

DEFAULT_VALUE_XX 는 원래 의도대로 살리고, util 형태로 사용하도록 수정하겠습니다.

2020-12-31 07:56 UTC, holykss commented on mediaProjectionLibrary/src/main/java/tech/thdev/media_projection_library/ui/MediaProjectionAccessService.kt
> +                height: Int = DeviceSize(context).size.height
DEFALUT_VALUE 로 돌리고, 외부에서 width/height 넘기도록 하겠습니다.

2021-01-01 12:18 UTC, taehwandev commented on mediaProjectionLibrary/src/main/java/tech/thdev/media_projection_library/util/DeviceSize.kt
> +class DeviceSize(context: Context) {
저 역시 코드에 대한 설명이 부족한 것 같아서 추가로 적어둡니다.

- class에서 context를 가지고 있는 형태는 추후 리팩토링 및 새로운 사람의 코드 작성시 문제가 될 수 있습니다.
- 현재는 들고 있지 않기는 하지만(val이 없어서) Util이 아닌 DiviceSize라는 이름을 사용햇기에 충분히 들고 있도록 변경 가능성이 있습니다.
- 이런 이유로 명확하게 유틸이라면 Util 형태로 만들어주어야 합니다.
- kotlin이기에 추천하는 방법은 kotlin extensions의 형태가 좋을것 같습니다.
- width, height를 바로 가져오도록 만드는것도 방법일거구요.
- 추가로 적용하신 코드를 Default 변수에 사용했는데, 이 역시 좋지 않은 사용법이라고 생각됩니다. 차라리 default를 제거하고, 무조건 주입을 유도하는게 좋은 방법이라고 생각합니다.
- 첫 의도는 사용하는 곳에서 변경해서 쓰라는 의미였습니다. 이 부분을 수정하신걸로 보아 제가 잘못 작성한것으로 보이네요.

2021-01-01 12:20 UTC, taehwandev approved these changes
첫 PR 감사합니다. 
제가 준비를 못한것 같은데, 다음엔 이슈도 함께 생성해주시면 더 좋을것 같습니다.

2021-01-01 12:20 UTC, merged

2021-01-01 15:34 UTC, holykss commented on mediaProjectionLibrary/src/main/java/tech/thdev/media_projection_library/util/DeviceSize.kt
> +class DeviceSize(context: Context) {
width/height 때문에 정상적으로 작동하지 않는 이슈가 있어서 일단 돌아가게 하는것에 치중하고 성급하게 PR 을 올린것 같습니다.
샘플이라는 이유도 어느 정도는 차지하고 있을것 같구요.
그래도 진지하게 피드백 주신 덕분에 여러가지를 생각하게 되었습니다.
가장 크게 드는 생각은 width/height parameters 는 DEFAULT parameter 로는 어울리지 않는다는 것이었습니다.
그리고, 나머지들은 제가 놓친 부분들에 대한 것이어서 감사하게 생각하고 있습니다.

2021-01-01 15:35 UTC, holykss commented
> 첫 PR 감사합니다.
> 제가 준비를 못한것 같은데, 다음엔 이슈도 함께 생성해주시면 더 좋을것 같습니다.

아닙니다. 이 샘플 덕분에 편하게 테스트 잘 했습니다.
추후에는 이슈를 활용해보겠습니다.
피드백 및 코드 반영 감사합니다.